type User @table {
  publicKey: String!
  username: String!
  createdAt: Timestamp!
  bio: String
  avatarUrl: String
  reputationScore: Int
}

type Resource @table {
  name: String!
  description: String!
  category: String!
  availabilityStatus: String!
  createdAt: Timestamp!
  owner: User
  imageUrls: [String]
  location: String
  usageTerms: String
}

type Request @table {
  requestedAt: Timestamp!
  status: String!
  startDate: Date!
  endDate: Date!
  requester: User
  resource: Resource
  message: String
}

type Transaction @table {
  transactionHash: String!
  createdAt: Timestamp!
  status: String!
  requester: User
  owner: User
  resource: Resource
  request: Request
}

type Feedback @table {
  rating: Int!
  createdAt: Timestamp!
  feedbackType: String!
  reviewer: User
  subjectUser: User
  subjectResource: Resource
  transaction: Transaction
  comment: String
}